# EndpointScouter Configuration
---
# Global settings
settings:
  timeout: 5  # Request timeout in seconds
  max_workers: 10  # Maximum parallel workers
  user_agent: "EndpointScouter/1.0"  # User agent string
  debug: false  # Enable debug logging
  rate_limit_test_count: 10  # Number of requests to test rate limiting

# Tests to run on all endpoints
tests:
  security_headers: true  # Check for security headers
  cors_headers: true  # Check CORS configuration
  rate_limiting: true  # Test for rate limiting
  vulnerability_scan: true  # Check for common vulnerabilities
  server_info: true  # Check for server information disclosure
  test_open_redirect: true  # Test for open redirect vulnerabilities
  test_directory_listing: true  # Test for directory listing vulnerabilities

# List of endpoints to scan
endpoints:
  - url: https://httpbin.org/get
    method: GET
    headers:
      User-Agent: "EndpointScouter Test"
    tags: ["test", "http"]
    
  - url: https://httpbin.org/headers
    method: GET
    tags: ["test", "headers"]
    
  - url: https://httpbin.org/status/418
    method: GET
    tags: ["test", "status"]